/var/log/onlyoffice/documentserver/*.log {
    daily
    missingok
    rotate 7
    compress
    delaycompress
    notifempty
    create 640 ds ds
    sharedscripts
    postrotate
        systemctl reload ds-docservice ds-converter ds-metrics >/dev/null 2>/dev/null || true
    endscript
}
