deployment:
  base_domain: example.com
  nextcloud_domain: docs.example.com
  onlyoffice_domain: onlyoffice.example.com
  admin_email: admin@example.com
  letsencrypt_email: admin@example.com
  nextcloud_admin_user: admin
  nextcloud_admin_password: CHANGE_ME_TO_SECURE_VALUE
nextcloud:
  db_name: nextcloud
  db_user: ncuser
  db_password: CHANGE_ME_TO_SECURE_VALUE
onlyoffice:
  db_name: onlyoffice
  db_user: oouser
  db_password: CHANGE_ME_TO_SECURE_VALUE
jwt:
  secret: "0000000000000000000000000000000000000000000000000000000000000000"
